### ISSUE TITLE
obuspa is not supporting dbadd command

### ISSUE THREAD

**Issue by rengaqck** [BroadbandForum/obuspa-test-controller#1]
I am trying to establish usp controller database along with MQTT instance.

After executing this command in my system, getting errors.
obuspa -c dbadd "Device.MQTT.Client.1."

```
$ obuspa -i eno1 -c dbadd "Device.MQTT.Client.1."
Running command on database /usr/local/var/obuspa/usp.db
ERROR: Unknown command: dbadd
```

I also looked into the source code whether **dbadd** is available or not. Looks like its not implemented.

So, how to add new instance within USP controller database.
Please help me to get some directions.

**Comment by holme-r** [comment]
There is no need for a 'dbadd' command. The database stores parameter-value pairs only. Just set values for the parameters of the object you want to add using 'dbset'.
