### ISSUE TITLE
Getting Warnings while running obuspa command in test controller

### ISSUE THREAD

**Issue by M0ulinamary** [BroadbandForum/obuspa-test-controller#2]
When i run the below command, i get the given warnings.
**controller:~/obuspa# obuspa -p -v 4 -r factory_reset_example.txt -i eth0**
DATABASE_Init: Opening database /usr/local/var/obuspa/usp.db
DEVICE_CONTROLLER_Start: WARNING: No instances in Device.LocalAgent.Controller
LoadClientCert: Not using a device certificate for connections
WARNING: No enabled MTPs in Device.LocalAgent.MTP. USP Agent may only be usable via the CLI

**Comment by holme-r** [comment]
The '-r' option only creates a database if one does not already exist (it specifies the factory reset settings). Probably you ran obuspa without the -r option, which then created an empty database. Subsequent use of the -r option will not override the empty database in this case.
To fix this, try deleting /usr/local/var/obuspa/usp.db, then invoking with the -r option.
If you make changes to factory_reset_example.txt, then you must delete /usr/local/var/obuspa/usp.db.

**Comment by M0ulinamary** [comment]
Resolved after updating proper data in the factory rest file while starting controller/agents.

Hence closing the ticket.
